---

- name: Get packages
  check_mode: false
  ansible.builtin.package_facts:

- name: Get services
  check_mode: false
  ansible.builtin.service_facts:

- name: Upgrade packages (dnf)
  when: ansible_pkg_mgr == "dnf"
  register: patchingresult_dnf
  ansible.builtin.package:
    name: '*'
    state: latest  # noqa: package-latest - Intended to update packages to latest
    exclude: "{{ exclude_packages }}"

- name: Check to see if we need a reboot
  register: result
  changed_when: result.rc == 1
  failed_when: result.rc > 1
  check_mode: false
  ansible.builtin.command: needs-restarting -r

- name: Reboot Server if Necessary
  when:
    - result.rc == 1
    - allow_reboot
  ansible.builtin.reboot:
