---

- name: Linux server patching
  hosts: "{{ _hosts | default(omit) }}"
  become: true

  tasks:
    # Install yum-utils if it's not there
    - name: Install yum-utils
      ansible.builtin.package:
        name: yum-utils
        state: installed
      check_mode: false

    - name: Include patching role
      ansible.builtin.include_role:
        name: demo.patching.linux

    - name: Tell user when Insights Client is not configured
      ansible.builtin.debug:
        msg: "Insights client does not appear to be configured. Scan will be skipped"
      when:
        - ansible_local.insights.system_id is not defined

    - name: Run the Insights Client Scan  # noqa: no-changed-when
      when:
        - not ansible_check_mode
        - ansible_local.insights.system_id is defined
      ansible.builtin.command: insights-client

    - name: Start firewalld
      ansible.builtin.service:
        name: firewalld
        state: started

    - name: Enable firewall http service
      loop:
        - http
        - https
      ansible.posix.firewalld:
        service: '{{ item }}'
        state: enabled
        immediate: true
        permanent: true
