---
user_message:
  - Update the 'activation_key' and 'org_id' extra variables for 'LINUX / Register with Insights'. https://access.redhat.com/management/activation_keys
  - Update Credential for Insights Inventory with Red Hat account.
  - Add variables for system_roles. https://console.redhat.com/ansible/automation-hub/repo/published/redhat/rhel_system_roles

# "!unsafe" used to pass raw jinja2 through to the injector definition, see
# https://github.com/redhat-cop/controller_configuration/tree/devel/roles/credential_types#formating-injectors
controller_credential_types:
  - name: Insights Collection
    kind: cloud
    inputs:
      fields:
        - id: insights_user
          type: string
          label: Insights User
        - id: insights_password
          type: string
          label: Insights Password
          secret: true
    injectors:
      env:
        INSIGHTS_USER: !unsafe '{{ insights_user }}'
        INSIGHTS_PASSWORD: !unsafe '{{ insights_password }}'

controller_credentials:
  - name: Insights Inventory
    credential_type: Insights Collection
    organization: Default
    state: exists
    inputs:
      insights_user: REPLACEME
      insights_password: REPLACEME

controller_inventory_sources:
  - name: Insights Inventory
    inventory: Home Lab
    source: scm
    source_project: Ansible Product Demos
    source_path: linux/inventory.insights.yml
    credential: Insights Inventory

controller_templates:
  - name: "Linux | Troubleshoot"
    job_type: run
    inventory: "Home Lab"
    project: "Personal | AAP Demos"
    playbook: "playbooks_linux/tshoot.yml"
    use_fact_cache: true
    credentials:
      - "Linux"
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Server Name or Pattern
          type: text
          variable: _hosts
          required: true

  - name: "Linux | Patching"
    job_type: check
    inventory: "Home Lab"
    project: "Personal | AAP Demos"
    playbook: "playbooks_linux/patching.yml"
    execution_environment: Default execution environment
    use_fact_cache: true
    ask_job_type_on_launch: true
    credentials:
      - "Linux"
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Server Name or Pattern
          type: text
          variable: _hosts
          required: true
  
  - name: "Linux | Run Shell Script"
    job_type: run
    inventory: "Home Lab"
    project: "Personal | AAP Demos"
    playbook: "playbooks_linux/run_script.yml"
    credentials:
      - "Linux"
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Server Name or Pattern
          type: text
          variable: _hosts
          required: true
        - question_name: Shell Script
          type: textarea
          variable: shell_script
          required: true

  - name: "Linux | Fact Scan"
    project: "Personal | AAP Demos"
    playbook: playbooks_linux/fact_scan.yml
    inventory: Home Lab
    execution_environment: Default execution environment
    use_fact_cache: true
    credentials:
      - Linux
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Server Name or Pattern
          type: text
          variable: _hosts
          required: true

  - name: "Linux | Podman Web Server"
    job_type: run
    inventory: "Home Lab"
    project: "Personal | AAP Demos"
    playbook: "playbooks_playbooks_linux/podman.yml"
    credentials:
      - "Linux"
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: Server Name or Pattern
          type: text
          variable: _hosts
          required: true
        - question_name: Web Page Message
          type: textarea
          variable: message
          required: true
          default: "This is Apache webserver running in a container with podman"
